services:
  auth:
    image: kitchana/auth
    build:
      context: https://github.com/lgcns-mini-proejct2-kitchana/Kitchana-Authentication.git
    environment:
      MYSQL_DATABASE: ${MYSQL_AUTH_DATABASE}
      MYSQL_USER: ${MYSQL_AUTH_USER}
      MYSQL_PASSWORD: ${MYSQL_AUTH_PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
      TOKEN_EXPIRATION_TIME: ${TOKEN_EXPIRATION_TIME}
      TEST_USER_PASSWORD: ${TEST_USER_PASSWORD}
      TEST_ADMIN_PASSWORD: ${TEST_ADMIN_PASSWORD}
    container_name: auth
    networks:
      - kitchana_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
    expose:
      - "8091"
    restart: on-failure

  article:
    image: kitchana/article
    build:
      context: https://github.com/lgcns-mini-proejct2-kitchana/Kitchana-Article.git
    environment:
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      GROQ_API_KEY: ${GROQ_API_KEY}
    container_name: article
    networks:
      - kitchana_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8092/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
    expose:
      - "8092"
    restart: on-failure

  board:
    image: kitchana/board
    build:
      context: https://github.com/lgcns-mini-proejct2-kitchana/Kitchana-Board.git
    environment:
      MYSQL_DATABASE: ${MYSQL_BOARD_DATABASE}
      MYSQL_USER: ${MYSQL_BOARD_USER}
      MYSQL_PASSWORD: ${MYSQL_BOARD_PASSWORD}
    container_name: board
    networks:
      - kitchana_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8093/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
    expose:
      - "8093"
    restart: on-failure

  frontend:
    image: kitchana/frontend
    build:
      context: https://github.com/lgcns-mini-proejct2-kitchana/Kitchana-FE.git
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      auth:
        condition: service_healthy
    restart: on-failure

networks:
  kitchana_network:
    external: true